name: Deploy

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:

  deploy:
    if: github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'main'
    runs-on: ubuntu-latest

    env:
      IMAGE_VERSION: ${{ github.run_number }}
    
    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Construindo container
      run: docker build . --file Dockerfile --tag uken49/web-fastlog:${{ env.IMAGE_VERSION }}
  
    - name: Enviando imagem para Docker Hub
      run: docker push uken49/web-fastlog:${{ env.IMAGE_VERSION }}
